In [2]:
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv('../data/asia10K.csv')

In [5]:

dataset

,Smoker,LungCancer,VisitToAsia,Tuberculosis,TuberculosisOrCancer,X-ray,Bronchitis,Dyspnea
0,yes,yes,no,no,yes,yes,yes,yes
1,no,no,no,no,no,yes,yes,yes
2,no,no,no,no,no,no,yes,yes
3,no,no,no,no,no,no,yes,yes
4,yes,no,no,no,no,no,yes,no
...,...,...,...,...,...,...,...,...
9995,no,no,no,no,no,no,no,no
9996,no,no,no,no,no,no,no,no
9997,no,no,no,no,no,no,no,no
9998,no,no,no,no,no,no,no,no
9999,yes,no,no,no,no,no,yes,yes